### ISSUE TITLE
ĐIỂM DANH LẸ

### ISSUE THREAD

**Issue by HaiDanggggggg** [HaiDanggggggg/Lop-11A16-Nhom-6#1]
Trần Hải Đăng

**Comment by CaoGiaPhu** [comment]
alo ông

**Comment by 29lethaonguyen11a16** [comment]
helo cả nhà iu

**Comment by HuynhTanBinhMinh** [comment]
trấm

**Comment by GiaKietttttt** [comment]
tại sao phải đỉm danh?

**Comment by HuynhTanBinhMinh** [comment]
ohaiyooo

**Comment by GiaKietttttt** [comment]
ngó pụi phắc cắp lụy mon lụy mon hãy dậu

**Comment by HienCaoPhuNhuan** [comment]
@HaiDanggggggg con hướng dẫn các nhóm khác làm nhé, nhóm làm tốt đó

**Comment by HuynhTanBinhMinh** [comment]
cho t gửi nhờ tấm hình

**Comment by HaiDanggggggg** [comment]
ăn ban nhó @HuynhTanBinhMinh

**Comment by CaoGiaPhu** [comment]
Hú, cho tui xí cái câu mà đèn bật 2 giây, tắt 1 giây nha
